// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeManager.Api.Persistance;

#nullable disable

namespace RecipeManager.Api.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221202031_AddBaseUnitAndUnitConversionsToIngredient")]
    partial class AddBaseUnitAndUnitConversionsToIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeManager.Api.Domain.Cookbooks.Cookbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cookbook", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Cookbooks.CookbookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CookbookId");

                    b.HasIndex("ParentId");

                    b.ToTable("CookbookCategory", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseUnit")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ShoppingListCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NutritionalValue", "RecipeManager.Api.Domain.Ingredients.Ingredient.NutritionalValue#NutritionalValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Calories");

                            b1.Property<double>("Carbohydrates");

                            b1.Property<double>("Fats");

                            b1.Property<int>("IngredientAmount");

                            b1.Property<Guid>("IngredientUnit");

                            b1.Property<double>("Proteins");

                            b1.ToJson("NutritionalValue");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BaseUnit");

                    b.HasIndex("ShoppingListCategoryId");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Ingredients.IngredientCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("IngredientCategory", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Ingredients.IngredientUnitConvertion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ratio")
                        .HasColumnType("float");

                    b.Property<Guid>("UnitToConvertId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitToConvertId");

                    b.ToTable("IngredientUnitConversion", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.MealPlan.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MealPlans", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NumberOfServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NutritionalValue", "RecipeManager.Api.Domain.Recipes.Recipe.NutritionalValue#NutritionalValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Calories");

                            b1.Property<double>("Carbohydrates");

                            b1.Property<double>("Fats");

                            b1.Property<int>("IngredientAmount");

                            b1.Property<Guid>("IngredientUnit");

                            b1.Property<double>("Proteins");

                            b1.ToJson("NutritionalValue");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Recipes.RecipeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategory", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredient", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConversionFactor")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PluralName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("PluralShortName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("PrimaryUnit")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryUnit");

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Cookbooks.CookbookCategory", b =>
                {
                    b.HasOne("RecipeManager.Api.Domain.Cookbooks.Cookbook", "Cookbook")
                        .WithMany("Categories")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Domain.Cookbooks.CookbookCategory", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsMany("RecipeManager.Api.Domain.Recipes.RecipeId", "Recipes", b1 =>
                        {
                            b1.Property<Guid>("CookbookCategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("CookbookCategoryId", "Id");

                            b1.ToTable("CookbookCategoryToRecipe", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CookbookCategoryId");
                        });

                    b.Navigation("Cookbook");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Ingredients.Ingredient", b =>
                {
                    b.HasOne("RecipeManager.Api.Domain.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("BaseUnit");

                    b.HasOne("RecipeManager.Api.Domain.Ingredients.IngredientCategory", null)
                        .WithMany()
                        .HasForeignKey("ShoppingListCategoryId");

                    b.OwnsMany("RecipeManager.Api.Domain.Recipes.RecipeId", "Recipes", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("IngredientId", "Id");

                            b1.ToTable("IngredientToRecipe", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.OwnsMany("RecipeManager.Api.Domain.Ingredients.IngredientCategoryId", "Categories", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("IngredientId", "Id");

                            b1.ToTable("IngredientToIngredientCategory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("Categories");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Ingredients.IngredientUnitConvertion", b =>
                {
                    b.HasOne("RecipeManager.Api.Domain.Ingredients.Ingredient", null)
                        .WithMany("IngredientUnitConvertions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Domain.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitToConvertId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.MealPlan.MealPlan", b =>
                {
                    b.OwnsMany("RecipeManager.Api.Domain.Recipes.RecipeId", "Recipes", b1 =>
                        {
                            b1.Property<Guid>("MealPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("MealPlanId", "Id");

                            b1.ToTable("RecipeToMealPlan", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MealPlanId");
                        });

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("RecipeManager.Api.Domain.Ingredients.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("RecipeManager.Api.Domain.Recipes.RecipeCategoryId", "Categories", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("RecipeToRecipeCategory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("RecipeManager.Api.Domain.Recipes.ValueObjects.RecipeAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Amount")
                                .HasColumnType("float")
                                .HasColumnName("Amount");

                            b1.Property<Guid?>("UnitId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RecipeId");

                            b1.HasIndex("UnitId");

                            b1.ToTable("Recipe");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.HasOne("RecipeManager.Api.Domain.Units.Unit", "Unit")
                                .WithMany()
                                .HasForeignKey("UnitId");

                            b1.Navigation("Unit");
                        });

                    b.OwnsMany("RecipeManager.Api.Domain.Recipes.ValueObjects.RecipeSection", "Sections", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeSection", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsMany("RecipeManager.Api.Domain.Recipes.ValueObjects.RecipeStep", "Steps", b2 =>
                                {
                                    b2.Property<int>("RecipeSectionId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("StepDescription");

                                    b2.Property<string>("ImageUrl")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("StepImage");

                                    b2.Property<int>("Order")
                                        .HasColumnType("int")
                                        .HasColumnName("StepOrder");

                                    b2.HasKey("RecipeSectionId", "Id");

                                    b2.ToTable("RecipeSectionStep", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeSectionId");
                                });

                            b1.Navigation("Steps");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeManager.Api.Domain.Ingredients.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Domain.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Units.Unit", b =>
                {
                    b.HasOne("RecipeManager.Api.Domain.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("PrimaryUnit")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Cookbooks.Cookbook", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Cookbooks.CookbookCategory", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Ingredients.Ingredient", b =>
                {
                    b.Navigation("IngredientUnitConvertions");
                });

            modelBuilder.Entity("RecipeManager.Api.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
